# Generation of a labeled quantum dataset

Here, I will generate a labeled (separable or entangled) quantum dataset, using the two procedures described in [this paper](https://www.nature.com/articles/s41598-023-28745-3)

In [1]:
import numpy as np

### Method 1

Generate quantum states as
$$\rho_{\theta,\,\phi} = p\left|\psi_{\theta,\,\phi}\right>\left<\psi_{\theta,\,\phi}\right| + (1 - p)\frac{I}{4}$$
With
$$\left|\psi_{\theta,\,\phi}\right> = \cos{\frac{\theta}{2}}\left|01\right> + e^{i\phi} \sin{\frac{\theta}{2}}\left|10\right>$$

In [50]:
theta = np.random.rand() * 2 * np.pi
phi = np.random.rand() * 2 * np.pi
theta, phi

(1.7275200680505278, 2.361036255727827)

In [53]:
sin_theta = np.sin(theta)
cos_theta = np.cos(theta)

exp_phi = np.exp(1j * phi)

sin_theta, cos_theta, exp_phi

(0.9877439517288035,
 -0.15608294533089506,
 (-0.7105221248254598+0.7036748610924748j))

In [62]:
basis = np.array([(0, 1), (1, 0), (0, 0), (1, 1)])

array([0, 1])

In [68]:
state1 = cos_theta * basis[0] + exp_phi * sin_theta * basis[1]
state2 = cos_theta * basis[2] + exp_phi * sin_theta * basis[3]

state1, state2

(array([-0.70181393+0.69505059j, -0.15608295+0.j        ]),
 array([-0.70181393+0.69505059j, -0.70181393+0.69505059j]))

### Method 2

Generate entangled states using random density matrices, that are hermitian matrices such that their trace is equal to 1

In [11]:
def generate_hermitian_product_states(size, n_matrices):
    
    product_states = []
    for _ in range(n_matrices):
        real_part = np.random.rand(size, size)
        imag_part = np.random.rand(size, size)
        product_state = real_part + 1j * imag_part
        product_state = np.matmul(product_state, product_state.conj().T)
        product_state /= np.trace(product_state)
        product_states.append(product_state)
        
    return np.array(product_states)

In [12]:
matrices = generate_hermitian_product_states(size=3, n_matrices=2)

matrices

array([[[0.39956837+0.j        , 0.24929193-0.08410831j,
         0.25093194-0.18063393j],
        [0.24929193+0.08410831j, 0.33984906+0.j        ,
         0.24672089-0.07853808j],
        [0.25093194+0.18063393j, 0.24672089+0.07853808j,
         0.26058257+0.j        ]],

       [[0.21993132+0.j        , 0.26216897-0.00441569j,
         0.26282109+0.03656981j],
        [0.26216897+0.00441569j, 0.35548601+0.j        ,
         0.36707519+0.07265365j],
        [0.26282109-0.03656981j, 0.36707519-0.07265365j,
         0.42458268+0.j        ]]])

In [13]:
np.kron(matrices[0], matrices[1])

array([[0.0878776 +0.j        , 0.10475443-0.00176437j,
        0.10501499+0.01461214j, 0.0548271 -0.01849805j,
        0.06498521-0.02315139j, 0.068595  -0.01298888j,
        0.05518779-0.03972706j, 0.06498895-0.04846465j,
        0.07255596-0.03829787j],
       [0.10475443+0.00176437j, 0.14204096+0.j        ,
        0.14667164+0.0290301j , 0.06572801-0.02094979j,
        0.08861979-0.02989933j, 0.09761966-0.01276211j,
        0.06658419-0.04624858j, 0.08920279-0.06421284j,
        0.10523461-0.04807511j],
       [0.10501499-0.01461214j, 0.14667164-0.0290301j ,
        0.16964981+0.j        , 0.06244335-0.031222j  ,
        0.08539811-0.04898604j, 0.10584503-0.03571093j,
        0.05934446-0.05665094j, 0.07898718-0.08453736j,
        0.10654136-0.07669404j],
       [0.0548271 +0.01849805j, 0.06572801+0.02094979j,
        0.06244335+0.031222j  , 0.07474345+0.j        ,
        0.08909788-0.00150067j, 0.0893195 +0.01242822j,
        0.05426165-0.01727298j, 0.06433576-0.02167969j,
     